# This workflow runs the US News scripts

name: scripts_run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  csvrefresh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3   

      # Set up python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'

      # Install dependencies
      - run: pip install -r requirements.txt     
          
      # Run jbscal.py        
      - run: python usnews_philly.py 
        working-directory: ./scripts

      # Push changes
      - name: push changes to remote
        run: |
          git config --global user.name "Amanda Kreider"
          git config --global user.email "akreid@wharton.upenn.edu"  

          git add ./csv/hosp_rankings_phila_pa.csv
          git commit -m "Update Philadelphia hospital rankings file"
          git pull --rebase
          git push          


